services:
  - type: web
    name: multiplayer-cursor-frontend
    runtime: static
    buildCommand: cd client && npm run build
    staticPublishPath: client/dist
    pullRequestPreviewsEnabled: true
    envVars:
      - key: VITE_WS_URL
        sync: false